version: "3"
services:
  postgres-db:
    container_name: db_gbteam
    image: postgres:latest
    restart: always
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gbteam_app
    ports:
      - "5432:5432"